name: Update JSON

on:
  schedule:
    - cron: "0 0 * * *"  # Täglich um Mitternacht UTC

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v2

    - name: Python einrichten
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Abhängigkeiten installieren
      run: |
        pip install selenium
        pip install webdriver_manager

    - name: Python-Script ausführen
      run: python update_json.py

    - name: Änderungen committen und pushen
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add strommix_2025.json
        git commit -m "Automated update of strommix_2025.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
